name: exmed-bert
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.11
  - pip
  # Core ML dependencies
  - pytorch=1.10.0
  - cudatoolkit=11.1
  - transformers=4.24.0
  - scikit-learn=1.1.3
  - xgboost=1.5.0
  - optuna=2.10.0
  - cloudpickle=2.2.0
  - cmaes=0.9.0
  # Data processing and visualization
  - pandas=1.3.4
  - numpy=1.22.3
  - matplotlib=3.5.0
  - seaborn=0.11.2
  - cycler=0.11.0
  # MLOps and experiment tracking
  - mlflow=1.30.0
  - hydra-core=1.1.1
  - joblib=1.2.0
  - alembic=1.8.1
  - databricks-cli=0.17.3
  - mako
  - importlib-metadata>=4.4
  - prettytable>=0.7.2
  - stevedore>=2.0.1
  # Development tools
  - black=22.10.0
  - flake8=5.0.4
  - mypy=0.990
  - ipython=8.6.0
  - colorama=0.4.6
  - ipywidgets=8.1.7
  - six
  - jinja2>=2.10.3
  # Additional pip packages
  - pip:
    - click==8.0.3
    - "typer[all]==0.6.1"  # Updated to include all dependencies
    - psmpy==0.3.13
    - multipledispatch==0.6.0
    - sqlalchemy==1.4.44
    - sqlalchemy-utils==0.38.3
    - pandas-stubs==1.5.1.221024
    - commitizen==2.37.0
    - vulture==2.6
    - pyperclip>=1.6
    - wcwidth>=0.1.7
    - antlr4-python3-runtime==4.8
    - autopage>=0.5.1
    - cliff>=4.0.0
    - colorlog>=6.7.0
    - decli>=0.5.2,<0.6.0
    - questionary>=1.4.0,<2.0.0
    - termcolor>=1.1,<3
    - pytype==2022.11.10
    - pyright==1.1.279
    - pyre-check==0.9.17
    - pyreadline3; platform_system == "Windows" 