name: exmed-bert
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.11
  - pip
  # Core ML dependencies
  - pytorch=1.10.0
  - transformers=4.24.0
  - scikit-learn=1.1.3
  - xgboost=1.5.0
  - optuna=2.10.0
  - cloudpickle=2.2.0
  - cmaes=0.9.0
  # Data processing and visualization
  - pandas=1.3.4
  - numpy=1.22.3
  - matplotlib=3.5.0
  - seaborn=0.11.2
  - cycler=0.11.0
  # MLOps and experiment tracking
  - mlflow=1.30.0
  - hydra-core=1.1.1
  - joblib=1.2.0
  - alembic=1.8.1
  - databricks-cli=0.17.3
  - mako
  - importlib-metadata>=4.4
  - prettytable>=0.7.2
  - stevedore>=2.0.1
  # Development tools
  - black=22.10.0
  - flake8=5.0.4
  - mypy=0.990
  - ipython=8.6.0
  - colorama=0.4.6
  - ipywidgets=8.1.7
  - six
  - jinja2>=2.10.3
  